/* Generated By:JavaCC: Do not edit this line. UnitsParserConstants.java */
package com.lgc.idh.util;

interface UnitsParserConstants {

  int EOF = 0;
  int PLUS = 3;
  int MINUS = 4;
  int MUL = 5;
  int DIV = 6;
  int POW = 7;
  int LP = 8;
  int RP = 9;
  int NAME = 10;
  int INTEGER = 11;
  int DOUBLE = 12;
  int ALPHA = 13;
  int LETTER = 14;
  int FLOAT = 15;
  int DIGIT = 16;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"+\"",
    "\"-\"",
    "<MUL>",
    "<DIV>",
    "<POW>",
    "\"(\"",
    "\")\"",
    "<NAME>",
    "<INTEGER>",
    "<DOUBLE>",
    "<ALPHA>",
    "<LETTER>",
    "<FLOAT>",
    "<DIGIT>",
  };

}
